# Generated by Django 5.1.1 on 2024-10-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='deliivery_status',
            new_name='delivery_status',
        ),
    ]
